[package]
name = "rust-rice-manager"
version = "1.0.1"
edition = "2024"

[[bin]]
name = "rrm"
path = "src/main.rs"

[dependencies]
clap = {version = "4.5.48", features = ["derive"] }
serde = {version="1.0.228",features=["derive"]}
serde_json = "1.0.145"
